version: "3.8"

services:
  db:
    image: mongo:4.0
    restart: always
    volumes:
      - db-data:/data/db
    ports: 
      - 27017:27017
    command: mongod --noauth --smallfiles
    # networks:
    #   - database-api
  api:
    container_name: api-hub
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: "atticusfinch123/atticus-literature-api"
    # volumes: 
    #   - /home/node/app/node_modules
    #   - ./backend:/home/node/app
    environment: 
      - MONGODB_URL=mongodb+srv://devHTTT2020:5T7Pr41EXIzDmWmi@cluster0.wfafv.mongodb.net/atticus-literature?retryWrites=true&w=majority
      # - MONGODB_URL=mongodb+srv://nam0908:JReu9aBIaQHAdAsK@cluster0.hhahn.mongodb.net/atticus-literature?retryWrites=true&w=majority
     # - MONGODB_URL=mongodb+srv://nam1304:6E82yABpvb9aHNz@cluster0.mg9jn.mongodb.net/atticus-literature
    # ports: 
      # - 5000:5000
    networks: 
      - api-client
  client:
    container_name: client-hub
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: "atticusfinch123/atticus-literature-client"
    # volumes: 
    #   - /home/node/app/node_modules
    #   - ./frontend:/home/node/app
    depends_on:
      - api
      - db
    # ports: 
    #   - 3000:3000
    networks: 
      - api-client
  revproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - api-client
    ports:
      - "80:80"
volumes:
    db-data:
        name: notes-db-dev-data
networks: 
    api-client:
        name: atticus-literature-network
        driver: bridge